name: RhythmExplorer

options:
  bundleIdPrefix: kall
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.4"

settings:
  base:
    DEVELOPMENT_TEAM: VG2GMCLCCR
    SWIFT_VERSION: "5.0"

targets:
  SuperSimple:
    type: application
    platform: iOS
    sources:
      - SuperSimple
    info:
      path: SuperSimple/Info.plist
      properties:
        CFBundleDisplayName: Rhythm Explorer
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~iphone:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        ITSAppUsesNonExemptEncryption: false
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: "1.0"
        PRODUCT_BUNDLE_IDENTIFIER: kall.RhythmExplorer
        PRODUCT_NAME: Rhythm Explorer
        TARGETED_DEVICE_FAMILY: "1,2"
