name: SuperSimple

options:
  bundleIdPrefix: kall
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.4"

settings:
  base:
    DEVELOPMENT_TEAM: VG2GMCLCCR
    SWIFT_VERSION: "5.0"

targets:
  SuperSimple:
    type: application
    platform: iOS
    sources:
      - SuperSimple
    info:
      path: SuperSimple/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~iphone:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSLocationWhenInUseUsageDescription: "Your location is used to show the distance to nearby cinemas."
        ITSAppUsesNonExemptEncryption: false
        TMDBAPIKey: "f0a9a713fef820c5075f2bd7de45eec5"
        TMDBReadAccessToken: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmMGE5YTcxM2ZlZjgyMGM1MDc1ZjJiZDdkZTQ1ZWVjNSIsIm5iZiI6MTUxOTU2NDU1OS43NjEsInN1YiI6IjVhOTJiNzBmOTI1MTQxMGIwMzAwOWY1YSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.SI4LBgi4rSe4pVE0ni5XWMdlE3CmjZtccuMOiVlbs64"
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: "1.0"
        PRODUCT_BUNDLE_IDENTIFIER: kall.SuperSimple
        TARGETED_DEVICE_FAMILY: "1,2"
